#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

typedef enum {
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, 
	RIGHT_BRACE, COMMA, DOT, MINUS, PLUS, 
	SEMICOLON, SLASH, STAR,

	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER,
	GREATER_EQUAL, LESS, LESS_EQUAL, AMPERSAND_AMPERSAND, 
	PIPE_PIPE,

	IDENTIFIER, STRING, NUMBER,

	CLASS, IF, ELSE, ELSEIF, TRUE, FALSE, FN, FOR, NIL, 
	PRINT, RETURN, SUPER, THIS, VAR, WHILE,

	ENDOFF
} TokenType;

#endif
